services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: "postgresql+asyncpg://postgres:password@db:5432/appdb"
    depends_on:
      db:
        condition: service_healthy
    user: "0:0"

  db:
    platform: linux/amd64
    image: postgres:17-alpine
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d appdb -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    user: "0:0"

volumes:
  data:
